//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Scores = new HashSet<Score>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public string ExperienceDetails { get; set; }
        public string ProgrammingLanguage { get; set; }
        public Nullable<double> TOEICscore { get; set; }
        public string Education { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
